### ISSUE TITLE
2 Issues I have

### ISSUE THREAD

**Issue by KoshikKumar17** [EvamariaTG/EvaMaria#127]
One, The person who has newly joined telegram can't start the bot...
There is no reply from the bot..

Other, If searching files inline is only for auth users...
What will I do so all can use it inline.

Please help..

**Comment by rakeshyt** [comment]
1 ussue--  Because Pyrogram Update,,

2 issue - auth users var leave as blank

**Comment by StillAliveTG** [comment]
> One, The person who has newly joined telegram can't start the bot... There is no reply from the bot..
> 
> Other, If searching files inline is only for auth users... What will I do so all can use it inline.
> 
> Please help..

Hey you KID say this thing in /https://t.me/EvaMariaSupport They will help you. Why opening an issue asking your foolish questions. Are You blind Read README.md. There is Given in LADIES FINGER letter SUPPORT and Under that its given Support Telegram Link also. Why are opening issues for such NOOBISH acts.
#saynotonoobishness

**Comment by subinps** [comment]
> One, The person who has newly joined telegram can't start the bot... There is no reply from the bot..
> 
> Other, If searching files inline is only for auth users... What will I do so all can use it inline.
> 
> Please help..

1. https://t.me/EvaMariaSupport/2597
2. https://t.me/EvaMariaSupport/12892
