### ISSUE TITLE
banned??????

### ISSUE THREAD

**Issue by sapthathsara** [EvamariaTG/EvaMaria#133]
Item could not be created:

    We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by NGROCKERS** [comment]
Yeah, my old accounts are banned from this issue, when i try to re install it show same message

**Comment by KoshikKumar17** [comment]
https://telegram.dog/XTZ_HerokuBot?start=RXZhbWFyaWFURy9FdmFNYXJpYSBtYXN0ZXI
