### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by KoshikKumar17** [EvamariaTG/EvaMaria#165]
As there is file store feature in the repo..
I request you developers that please add one more feature that admins of the bot can delete those files or batch files for which shareable link has been generated

**Comment by rahulrahamanx** [comment]
+1

**Comment by KoshikKumar17** [comment]
@subinps @Jijinr @SpEcHiDe @PhysicHybridTG @shamilhabeebnelli @Jack-of-tg 
Please help

**Comment by subinps** [comment]
> @subinps @Jijinr @SpEcHiDe @PhysicHybridTG @shamilhabeebnelli @Jack-of-tg Please help

U can send ₹2000 to my upi id and i will add that for u
