### ISSUE TITLE
Can't Deploy this repo on Railway.app

### ISSUE THREAD

**Issue by Joelkb** [EvamariaTG/EvaMaria#170]
I tried to deploy this repo on railway.app, but its failed and showing "**### Banned dependency found AUTO-FILTER-BOT Please remove this dependency from this repo to deploy it on railway**".

**_### Please help me to fix this issue..._**

**Comment by athul1706** [comment]
> clear Readme.md and deploy.. I'm not sure.but you can just try🙂

**Comment by xovoefx** [comment]
IF YOU CANT DEPLOY IT ON RAILWAY DEPLOY IT ON HEROKU
