### ISSUE TITLE
Pm problem, please help. 

### ISSUE THREAD

**Issue by Babyotush** [EvamariaTG/EvaMaria#175]
I was using subnips before, but now I switched to evamaria for my movie bot.

Right now the inline search is working, but the auto filter or pm filter is not responding. 
Like when I try to sending in the movie name, the bot isn't responding. But whenever I use inline mode, it will respond. Please walk me through this problem. Thank you.

**Comment by illuzX** [comment]
Check Out Ure Heroku/or Railway  Logs

**Comment by illuzX** [comment]
> I was using subnips before, but now I switched to evamaria for my movie bot.
> 
> Right now the inline search is working, but the auto filter or pm filter is not responding. Like when I try to sending in the movie name, the bot isn't responding. But whenever I use inline mode, it will respond. Please walk me through this problem. Thank you.

Check Out Ure Heroku/or Railway  Logs

**Comment by shamilhabeebnelli** [comment]
Double check the logs
