### ISSUE TITLE
Inline Mode 😶

### ISSUE THREAD

**Issue by HithaishiDesai** [EvamariaTG/EvaMaria#191]
#bug

Even though auth_users var is used on Heroku 

The bot allows everyone to use inline mode.

Thanks

**Comment by subinps** [comment]
https://github.com/EvamariaTG/EvaMaria/commit/17e08039d6f06c62c6cafd39c3f6deaf5697dcdd

**Comment by Jackandoggy** [comment]
#bug

If we batch get aa bot start link but we click on that it will show please wait and delete the message 
So we can't get batched files

Thanks
