### ISSUE TITLE
feature request: larger result buttons

### ISSUE THREAD

**Issue by HuzunluArtemis** [EvamariaTG/EvaMaria#22]
add an optional feature please. larger results will be better for reading.

at now:

![at now](https://user-images.githubusercontent.com/84624971/139601786-7af37bab-549d-4f96-a65f-96e2d09b5ce0.png)

add optional larger result buttons:

![resim](https://user-images.githubusercontent.com/84624971/139601808-04b7726e-3e58-48a1-bb1a-d946f1d3fdcd.png)

**Comment by mirrorclone** [comment]
@HuzunluArtemis yes this problem .articles are not read correctly

**Comment by subinps** [comment]
https://github.com/EvamariaTG/EvaMaria/commit/940a08880b061c504a8d5dcbf4d1de40af13d0bf

Add a var named SINGLE_BUTTON with value True
